pygments: true
markdown: kramdown
exclude: README, TODO
google_search_api_key: ABQIAAAA4FSoe3--17eX3cgfdvjKsRQ4IGXGPU5DOLSHk3zPGcPhlFXu1xTQgKfcR-UutP3ecbKlqQzsmPodgg
ga_id: UA-24044711-3

kramdown:
  auto_ids: true,
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
